#!/bin/bash

sudo dnf -y install ruby zsh make gcc ruby-devel git git-extras
sudo gem install YkLib binding_of_caller
git clone  https://github.com/Yougain/interim_installer.git
sudo cp interim_installer/lsr /usr/bin
sudo cp interim_installer/rb_zsh /usr/bin
sudo cp interim_installer/zshrc.local /etc

