#!/bin/bash



ssh_inst(){
	ssh -q -p 22 -o "PasswordAuthentication no" -o "StrictHostKeyChecking no" -o "UserKnownHostsFile /dev/null" -l rancher $@
}


install_ssh_key(){
	KEY=`cat ~/.ssh/id_ed25519.pub 2>/dev/null`
	if [ -z "$KEY" ];then
		err Cannot find public key in ~/.ssh/id_ed25519.pub.
	fi
	local SET_KEY_CNT=0
	while ! ssh_inst $1 echo; do
		if [ "$SET_KEY_CNT" = "5" ]; then
			return 1
		fi
		expect -c "
		set timeout 1
		spawn ssh -p 22 -o \"StrictHostKeyChecking no\" -o \"UserKnownHostsFile /dev/null\" -l rancher $1
		expect \"assword:\"
		send \"rancher\n\"
		expect \"rancher ~]$ \"
		send \"mkdir ~/.ssh\n\"
		expect \"rancher ~]$ \"
		send \"chmod 700 ~/.ssh\n\"
		expect \"rancher ~]$ \"
		send \"echo $KEY >> ~/.ssh/authorized_keys\n\"
		expect \"rancher ~]$ \"
		send \"exit\"
		"
		sleep 1
		SET_KEY_CNT=$(( SET_KEY_CNT + 1 ))
	done
	return 0
}


if [ -n "$1" ];then
	if ! ssh $1 -o ConnectTimeout=3 -o ConnectionAttempts=3 echo -n; then
		if ! ssh_inst $1 echo -n; then
			if ! install_ssh_key $1; then
				echo "Cannot logon as user, 'rancher' by password, 'rancher'.
Please enter following commands on console.
sudo passwd rancher
rancher
rancher"
			fi
		fi
		ssh_inst -t $1 'if [ -f /bin/dnf -o -f /usr/bin/dnf ];then IST="dnf"; else if [ -f /bin/yum -o -f /usr/bin/yum ];then IST="yum"; else if [ -f /usr/apt-get -o -f /usr/bin/apt-get ];then IST="apt-get"; else echo "Error: package installer not found."; exit 1; fi; fi; fi; if [ ! -f /bin/git ];then sudo $IST -y update; sudo $IST -y install git git-extras; fi; if [ ! -f /bin/which -a ! -f /usr/bin/which ];then sudo \$IST -y install which; fi; if [ -d "./interim_installer" ]; then git-force-clone  https://github.com/Yougain/interim_installer.git ~/interim_installer; else git clone https://github.com/Yougain/interim_installer.git; fi; ./interim_installer/'${0##*/}'; exit $?'
	else
		ssh -t $1 'if [ -f /bin/dnf -o -f /usr/bin/dnf ];then IST="dnf"; else if [ -f /bin/yum -o -f /usr/bin/yum ];then IST="yum"; else if [ -f /usr/apt-get -o -f /usr/bin/apt-get ];then IST="apt-get"; else echo "Error: package installer not found."; exit 1; fi; fi; fi; if [ ! -f /bin/git ];then sudo $IST -y update; sudo $IST -y install git git-extras; fi; if [ ! -f /bin/which -a ! -f /usr/bin/which ];then sudo \$IST -y install which; fi; if [ -d "./interim_installer" ]; then git-force-clone  https://github.com/Yougain/interim_installer.git ~/interim_installer; else git clone https://github.com/Yougain/interim_installer.git; fi; ./interim_installer/'${0##*/}'; exit $?'
	fi
	exit $?
fi


APKG_R="redhat-rpm-config epel-release glibc-locale-source langpacks-en glibc-langpack-en"
if [ -f /bin/dnf -o -f /usr/bin/dnf ];then
	IST="dnf"
	DVP="devel"
	APKG="$APKG_R"
else
	if [ -f /bin/yum -o -f /usr/bin/yum ];then
		IST="yum"
		DVP="devel"
		APKG="$APKG_R"
	else
		if [ -f /usr/apt-get -o -f /usr/bin/apt-get ];then
	        IST="apt-get"
			DVP="dev"
		else
			echo "Error: package installer not found."
			exit 1
		fi
	fi
fi


if [ ! -f /bin/git -a ! -f /usr/bin/git ];then
	sudo $IST -y install git
fi

if [ ! -f /bin/which -a ! -f /usr/bin/which ];then
    sudo $IST -y install which
fi

sudo $IST -y update
if [ "$IST" = "apt-get" ];then
	sudo DEBIAN_FRONTEND=noninteractive $IST -y upgrade -yq
else
	sudo $IST -y upgrade
fi


sudo $IST -y install vim cpio man ruby zsh make gcc ruby-$DVP git git-extras ncurses-$DVP $APKG
sudo gem install binding_of_caller curses
sudo gem install -N YkLib
GPRJ=~/git_project
GPAGE=https://github.com/Yougain

Git-Force-Clone-Inst(){
	while (( $# )); do
		git-force-clone $GPAGE/$1.git $GPRJ/$1
		if [ -x $GPRJ/$1/install ];then
			( cd $GPRJ/$1; ./install )
		fi
		shift
	done
}

Git-Force-Clone-Inst g bashlib_y


sudo ln -sf $GPRJ/interim_installer/lsr /usr/bin
sudo ln -sf $GPRJ/interim_installer/lsp /usr/bin
sudo ln -sf $GPRJ/interim_installer/zsh_rb /usr/bin
sudo ln -sf $GPRJ/interim_installer/addline /usr/bin
sudo ln -sf $GPRJ/interim_installer/usb_dev /usr/bin
sudo ln -sf $GPRJ/interim_installer/untar /usr/bin
sudo ln -sf $GPRJ/interim_installer/zshrc.local /etc

setup_home(){
	while [ "$#" != 0 ]; do
		echo $1
		if [ "$1" != "/home/*" ]; then
			sudo cp -fa $GPRJ/interim_installer/.vimrc $1
			sudo cp -fra $GPRJ/interim_installer/.vim $1
			sudo cp -fa $GPRJ/interim_installer/.zshrc $1
		fi
		shift
	done;
}

sudo update-alternatives --set editor /usr/bin/vim.basic

setup_home /etc/skel /root /home/*
sudo sed -i 's/bash/zsh/' /etc/passwd
sudo sed -i 's/SHELL=\/bin\/bash$/SHELL=\/bin\/zsh/' /etc/default/useradd

if [ ! -x '/bin/env' ]; then
	sudo ln -sf /usr/bin/env /bin
fi

if [ ! -e '/etc/zsh/zprofile' ];then
	sudo touch /etc/zsh/zprofile
fi


sudo addline /etc/zsh/zprofile <<END
for i in /etc/profile.d/*.sh ; do
	if [ "\$i" != "/etc/profile.d/bash_completion.sh" ]; then
    	[ -r \$i ] && source \$i
    fi
done
END

