#!/bin/bash

if [ -n "`which dnf`" ];then
	CMD="dnf"
else
	CMD="yum"
fi
if [ -n "`which git`" ];then
	sudo $CMD -y install git
fi

sudo $CMD -y install ruby zsh make gcc ruby-devel git git-extras
sudo gem install YkLib binding_of_caller
git-force-clone  https://github.com/Yougain/interim_installer.git ~/interim_installer


sudo cp $HOME/interim_installer/lsr /usr/bin
sudo cp $HOME/interim_installer/rb_zsh /usr/bin
sudo cp $HOME/interim_installer/addline /usr/bin

sudo cp $HOME/interim_installer/zshrc.local /etc

function setup_home(){
	while (( "$#" )); do
		sudo cp $HOME/interim_installer/.vimrc $1
		sudo cp -r $HOME/interim_installer/.vim $1
		shift
	done;
}

setup_home /etc/skel /root /home/*

