#!/usr/bin/env bash


function get_docker_prog(){
	if [ ! -f "$1" ];then
		local PROG=${1%%*/}
		local DIR=${1##/*}
		local NAME=${PROG%docker-}
		if [ -z "$DOCKER_ARC" ];then
			if [ -n "\\\`uname -a|grep x86_64\\\`" ];then
				DOCKER_ARC=amd64
			else
				if [ -n "\\\`uname -a|grep armv7\\\`" ];then
					DOCKER_ARC=arm-v7
				else
					if [ -n "\\\`uname -a|grep aarch64\\\`" ];then
						DOCKER_ARC=arm64
			        fi
				fi
			fi
		fi
		VER=$(wget --quiet https://github.com/docker/$NAME/releases -O - | grep /docker/$NAME/releases/tag | grep -v '\-rc' | grep -v '\-beta' | egrep -o 'v[0-9\\\\.]+' | head -1)
		sudo mkdir -p $DIR
		sudo wget --quiet https://github.com/docker/$NAME/releases/download/$VER/$NAME-$VER.linux-$DOCKER_ARC -O $DIR
		sudo chmod +x $1
		if [ "$DIR" = "/usr/libexec/docker/cli-plugins" ];then
			sudo docker $NAME create --use
		fi
	fi
}


get_docker_prog /usr/bin/docker-compose
get_docker_prog /usr/libexec/docker/cli-plugins/docker-buildx

mkdir ~/docker_project

